name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10"

      - name: Check that package version matches tag ref
        run: |
          pdm show --version
          echo "v$(pdm show --version) = ${{ github.ref_name }}"
          [ "v$(pdm show --version)" = "${{ github.ref_name }}" ]
        working-directory: ${{ github.workspace }}

      - name: Publish package (test)
        run: |
          pdm publish || true
        env:
          PDM_PUBLISH_REPO: "https://test.pypi.org/legacy/"
          PDM_PUBLISH_USERNAME: "__token__"
          PDM_PUBLISH_PASSWORD: "${{ secrets.PYPI_TEST_TOKEN }}"

      - name: Publish package
        run: |
          pdm publish
        env:
          PDM_PUBLISH_USERNAME: "__token__"
          PDM_PUBLISH_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
